services:
  - type: web
    name: my-express-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    ports:
      - port: 5000
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: ./mtbookig-bank.db
